modify macs2

diff --git a/Dockerfiles/scripts/churros_mapping b/Dockerfiles/scripts/churros_mapping
--- a/Dockerfiles/scripts/churros_mapping
+++ b/Dockerfiles/scripts/churros_mapping
@@ -2,9 +2,11 @@
 cmdname=`basename $0`
 function usage()
 {
-    echo "$cmdname" '[options] <exec|stats|header> <fastq> <prefix> <build> <Ddir>' 1>&2
+    echo "$cmdname" '[options] <command> <fastq> <prefix> <build> <Ddir>' 1>&2
     echo '   <command>:' 1>&2
-    echo '      exec: bowtie2, ssp and parse2wig+;' 1>&2
+    echo '      exec: map + postprocess' 1>&2
+    echo '      map: mapping by bowtie2' 1>&2
+    echo '      postprocess: QC and generate wig files by ssp and parse2wig;' 1>&2
     echo '      stats: show mapping/QC stats;' 1>&2
     echo '      header: print header line of the stats' 1>&2
     echo '   <fastq>: fastq file' 1>&2
@@ -14,6 +16,7 @@ function usage()
     echo '   Options:' 1>&2
     echo '      -c: output as CRAM format (defalt: BAM)' 1>&2
     echo '      -b: binsize of parse2wig+ (defalt: 100)' 1>&2
+    echo '      -z: peak file for FRiP calculation (BED format, default: default MACS2 without control)' 1>&2
     echo '      -m: consider genome mappability in parse2wig+' 1>&2
     echo '      -k [36|50]: read length of mappability file (default:50)' 1>&2
     echo '      -n: omit ssp' 1>&2
@@ -36,14 +39,23 @@ bamdir=bam
 of=3
 binsize=100
 k=50
-while getopts cb:mk:nf:p: option
+peak=""
+while getopts cb:z:a:mk:nf:p: option
 do
     case ${option} in
 	c) format=CRAM
 	   bamdir=cram
 	   ;;
 	b) binsize=${OPTARG};;
-        m) mp=1;;
+	z) peak=${OPTARG}
+           if test ! -e $peak; then
+               echo "Error: $peak does not exist (-b)."
+               exit 1
+           else
+               peak="--bed $peak"
+           fi
+           ;;
+	m) mp=1;;
 	k) k=${OPTARG};;
         n) nopp=1;;
         f) of=${OPTARG};;
@@ -100,19 +112,29 @@ else
     parseparam=""
 fi
 
-if test $command = "exec"; then
+if test $command = "map" -o $command = "exec"; then
+    if test $format = "CRAM"; then
+        bowtie2.sh -c -p "$bowtieparam" "$fastq" $prefix $build $Ddir
+    else
+        bowtie2.sh -p "$bowtieparam" "$fastq" $prefix $build $Ddir
+    fi
+fi
+if test $command = "postprocess" -o $command = "exec"; then
     if test $format = "CRAM"; then
        mapfile=$bamdir/$head.sort.cram
-       bowtie2.sh -c -p "$bowtieparam" "$fastq" $prefix $build $Ddir
-       parse2wig+.sh $parseparam $pair -b $binsize -f $of $mapfile $head $build $Ddir
+       parse2wig+.sh $parseparam $pair -b $binsize $peak -f $of $mapfile $head $build $Ddir
     else
-       # BAM
        mapfile=$bamdir/$head.sort.bam
-       bowtie2.sh -p "$bowtieparam" "$fastq" $prefix $build $Ddir
-       parse2wig+.sh $parseparam $pair -b $binsize -f $of $mapfile $head $build $Ddir
+       if test "$peak" != ""; then
+	   parse2wig+.sh $parseparam $pair -b $binsize $peak -f $of $mapfile $head $build $Ddir
+       else
+	   macs.sh $mapfile none ${prefix}_forFRiP sharp
+	   parse2wig+.sh $parseparam $pair -b $binsize -z macs/${prefix}_forFRiP_peaks.narrowPeak -f $of $mapfile $head $build $Ddir
+       fi
     fi
     if test $nopp != 1; then ssp.sh $pair $mapfile $head $build $gt; fi
-elif test $command = "stats"; then
+fi
+if test $command = "stats"; then
     a=`parsebowtielog2.pl $pair log/bowtie2-$head | grep -v Sample`
     b=`cat log/parsestats-$head.$binsize | grep -v Sample | cut -f6,7,8,9`
     gcov=`cat log/parsestats-$head.$binsize | grep -v Sample | cut -f10`
