update script to use Churros_result

diff --git a/Dockerfiles/scripts/churros b/Dockerfiles/scripts/churros
--- a/Dockerfiles/scripts/churros
+++ b/Dockerfiles/scripts/churros
@@ -22,6 +22,7 @@ function usage()
     echo '      -P "bowtie2 param": parameter of bowtie2 (shouled be quated)' 1>&2
     echo '      -p : number of CPUs (default: 12)' 1>&2
     echo '      -w : output ChIP/Input -log(p) distribution as a begraph format' 1>&2
+    echo '      -D outputdir: output dir (defalt: "Churros_result")' 1>&2
     echo "   Example:" 1>&2
     echo "      For single-end: $cmdname exec chip.fastq.gz chip hg38 Database/Ensembl-GRCh38" 1>&2
 }
@@ -39,7 +40,9 @@ ncore=12
 qval=0.05
 mdir=macs
 
-while getopts cb:mnf:P:p:q:d:w option
+chdir="Churros_result"
+
+while getopts cb:mnf:P:p:q:d:wD: option
 do
     case ${option} in
 	c) format=CRAM
@@ -54,6 +57,7 @@ do
 	q) qval=${OPTARG};;
         d) mdir=${OPTARG};;
 	w) outputpval=1;;
+        D) chdir=${OPTARG};;
 	*)
 	    usage
 	    exit 1
@@ -71,6 +75,16 @@ samplelist=$1
 samplepairlist=$2
 build=$3
 Ddir=$4
+
+if test ! -e $samplelist; then
+    echo "Error: $samplelist does not exist."
+    exit 1
+fi
+if test ! -e $samplepairlist; then
+    echo "Error: $samplepairlist does not exist."
+    exit 1
+fi
+
 
 if [[ ${samplelist} =~ ^/.+$ ]]; then
     n=1 # dummy
@@ -92,8 +106,6 @@ else
     parseparam=""
 fi
 
-pwd=`pwd`
-chdir=$pwd/Churros_result
 mkdir -p $chdir
 
 while read LINE; do
@@ -141,14 +153,16 @@ done < $samplepairlist
 churros_callpeak -b $chdir/bam -p $ncore -q $qval -d $chdir/$mdir $samplepairlist_withflen $build
 
 if test $outputpval -eq 1; then
-    mkdir -p drompa+.pval
+    echo "generate Pvalue bedGraph file..."
     gt=$Ddir/genometable.txt
     churros_genPvalwig -D $chdir $samplepairlist drompa+.pval $build $gt
 fi
 
 pdfdir=$chdir/pdf
 mkdir -p $pdfdir
+echo "generate pdf files by drompa+..."
 churros_visualize -D $chdir $chdir/$mdir/samplepairlist.txt $pdfdir/drompa+.macspeak $build $Ddir
 churros_visualize -D $chdir -b 5000 -l 8000 -P "--scale_tag 100" $samplepairlist $pdfdir/drompa+.bin5M $build $Ddir
 churros_visualize -D $chdir -b 5000 -l 8000 -p -P "--pthre_enrich 3 --scale_pvalue 3" $samplepairlist $pdfdir/drompa+.pval.bin5M $build $Ddir
 churros_visualize -D $chdir -G $samplepairlist $pdfdir/drompa+ $build $Ddir
+echo "done."
diff --git a/Dockerfiles/scripts/churros_callpeak b/Dockerfiles/scripts/churros_callpeak
--- a/Dockerfiles/scripts/churros_callpeak
+++ b/Dockerfiles/scripts/churros_callpeak
@@ -40,6 +40,11 @@ fi
 samplepairlist=$1
 build=$2
 
+if test ! -e $samplepairlist; then
+    echo "Error: $samplepairlist does not exist."
+    exit 1
+fi
+
 ex(){ echo $1; eval $1; }
 
 mkdir -p $mdir
diff --git a/Dockerfiles/scripts/churros_genPvalwig b/Dockerfiles/scripts/churros_genPvalwig
--- a/Dockerfiles/scripts/churros_genPvalwig
+++ b/Dockerfiles/scripts/churros_genPvalwig
@@ -11,7 +11,7 @@ function usage()
     echo '      -b <int>: binsize (defalt: 100)' 1>&2
     echo '      -d <str>: directory of parse2wig+ (default: parse2wigdir+)' 1>&2
     echo '      -y <str>: postfix of .bw files to be used (default: "-bowtie2-<build>-raw-GR")' 1>&2
-    echo '      -D <str>: output directory (defalt: ./)' 1>&2
+    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
     echo "   Example:" 1>&2
     echo "      $cmdname samplelist.txt chip-seq hg38 Database/Ensembl-GRCh38" 1>&2
 }
@@ -19,7 +19,7 @@ function usage()
 binsize=100
 pdir=parse2wigdir+
 post_predefined=""
-chdir="./"
+chdir="Churros_result"
 
 while getopts b:d:y:D: option
 do
@@ -46,10 +46,22 @@ odir=$2
 build=$3
 gt=$4
 
+if test ! -e $samplepairlist; then
+    echo "Error: $samplepairlist does not exist."
+    exit 1
+fi
+
 pdir=$chdir/$pdir
 logdir=$chdir/log
-mkdir -p $logdir
 odir=$chdir/$odir
+mkdir -p $logdir $odir
+
+if test ! -e $gt; then
+    echo "Error: $gt does not exist."
+    exit 1
+fi
+
+echo "output directory: $odir"
 
 if test "$post_predefined" = ""; then
     post=-bowtie2-$build-raw-GR
diff --git a/Dockerfiles/scripts/churros_mapping b/Dockerfiles/scripts/churros_mapping
--- a/Dockerfiles/scripts/churros_mapping
+++ b/Dockerfiles/scripts/churros_mapping
@@ -27,7 +27,7 @@ function usage()
     echo '               3: bigWig (.bw)' 1>&2
     echo '      -P "bowtie2 param": parameter of bowtie2 (shouled be quated)' 1>&2
     echo '      -p : number of CPUs (default: 12)' 1>&2
-    echo '      -D outputdir: output dir (defalt: ./)' 1>&2
+    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
     echo "   Example:" 1>&2
     echo "      For single-end: $cmdname exec chip.fastq.gz chip hg38 Database/Ensembl-GRCh38" 1>&2
     echo "      For paired-end: $cmdname exec \"-1 chip_1.fastq.gz -2 chip_2.fastq.gz\" chip hg38 Database/Ensembl-GRCh38" 1>&2
@@ -43,7 +43,7 @@ binsize=100
 k=50
 peak=""
 ncore=12
-chdir="./"
+chdir="Churros_result"
 
 while getopts cb:z:a:mk:nf:P:p:D: option
 do
@@ -112,6 +112,10 @@ if [[ $fastq == *-1\ * ]]; then
 fi
 
 gt=$Ddir/genometable.txt
+if test ! -e $gt; then
+    echo "Error: $gt does not exist. Please make it by 'download_genomedata.sh'."
+    exit 1
+fi
 
 parseparam="-D $chdir -t $ncore $pair -f $of"
 
diff --git a/Dockerfiles/scripts/churros_visualize b/Dockerfiles/scripts/churros_visualize
--- a/Dockerfiles/scripts/churros_visualize
+++ b/Dockerfiles/scripts/churros_visualize
@@ -15,7 +15,7 @@ function usage()
     echo '      -p: show p-value distribution instead of read distribution' 1>&2
     echo '      -P : additional parameters for DROMPA+ (shouled be quated)' 1>&2
     echo '      -G : genome-wide view (100kbp)' 1>&2
-    echo '      -D outputdir: output dir (defalt: ./)' 1>&2
+    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
     echo "   Example:" 1>&2
     echo "      $cmdname samplelist.txt chip-seq hg38 Database/Ensembl-GRCh38" 1>&2
 }
@@ -27,7 +27,7 @@ post_predefined=""
 GV=0
 showpvalue=0
 param=""
-chdir="./"
+chdir="Churros_result"
 
 while getopts P:b:l:d:o:y:pGD: option
 do
@@ -57,10 +57,12 @@ samplepairlist=$1
 prefix=$2
 build=$3
 Ddir=$4
-
 pdir=$chdir/$pdir
-logdir=$chdir/log
-mkdir -p $logdir
+
+if test ! -e $samplepairlist; then
+    echo "Error: $samplepairlist does not exist."
+    exit 1
+fi
 
 if test "$post_predefined" = ""; then
     post=-bowtie2-$build-raw-GR
@@ -75,6 +77,10 @@ fi
 ex(){ echo $1; eval $1; }
 
 gt=$Ddir/genometable.txt
+if test ! -e $gt; then
+    echo "Error: $gt does not exist. Please make it by 'download_genomedata.sh'."
+    exit 1
+fi
 
 if test $GV -eq 1; then
     # GV mode
@@ -98,7 +104,9 @@ if test $GV -eq 1; then
     done < $samplepairlist
 
     head=`basename $prefix`
-    ex "drompa+ GV $param $sGV -o $prefix.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 500000 >& $logdir/drompa+.$head.GV.100000"
+    echo "Command:"
+    echo "drompa+ GV $param $sGV -o $prefix.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 50000 >& $prefix.GV.100000.log" > $prefix.GV.100000.log
+    ex "drompa+ GV $param $sGV -o $prefix.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 500000 >> $prefix.GV.100000.log"
 else
     s=""
 #    while IFS=, read chip input label mode peak; do
@@ -118,6 +126,9 @@ else
 
     gene=$Ddir/gtf_chrUCSC/chr.gene.refFlat
     head=`basename $prefix`
-    ex "drompa+ PC_SHARP $param $s -o $prefix.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak >& $logdir/drompa+.$head.PCSHARP.$binsize"
+
+    echo "Command:"
+    echo "drompa+ PC_SHARP $param $s -o $prefix.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak >& $prefix.PCSHARP.$binsize.log" > $prefix.PCSHARP.$binsize.log
+    ex "drompa+ PC_SHARP $param $s -o $prefix.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak >> $prefix.PCSHARP.$binsize.log"
     rm $prefix.PCSHARP.$binsize.pdf
 fi
